### ISSUE TITLE
Client is already connected but does not retrieve any updates

### ISSUE THREAD

**Issue by unheal1337** [ParsePlatform/ParseLiveQuery-Android#17]
**Environment** 
Successfully installed Parse Server 2.3.7 on AWS Elastic Beanstalk with an Application Load Balancer listening on port 80 (HTTP). The load balancer does not use nginx proxy anymore (removed manuelly).

**Setup**
We are testing with the following html file https://blog.sashido.io/sashido-goes-realtime-with-parse-server-live-queries/
On that file subsciption is working fine on all event (open, update, ...). 

We want to use livequery on Android but we do not get any callback on any events, even no errors. In Android debugging mode the websockets client state is always CONNECTED.
The Live Query URL is :

`uri = new URI("ws://xxxx.us-east-1.elasticbeanstalk.com:80/1");`

ParseQuery gets initialized by:
```
ParseQuery<ParseObject> queryPost = ParseQuery.getQuery("Posts");
queryPost.whereEqualTo("text", "m");
```
We followed the README on **this** repo to initialize the LiveQuery Android client.

**Question**
What is going wrong with this implementation? Thanks for any help!
If you want to know any additional specifications, feel free to ask.

**Comment by mmimeault** [comment]
After creating you `queryPost`, do you subscribe to it? (eg. `parseLiveQueryClient.subscribe(queryPost)`)

Do you see any logs on the server side (in verbose).

Thanks.

**Comment by unheal1337** [comment]
Yes, we subscribe like:

```
try { 
	// Live Query URL
	uri = new URI("ws://xxxx.us-east-1.elasticbeanstalk.com:80/1");

	parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(uri);

	ParseQuery<ParseObject> queryPost = ParseQuery.getQuery("Posts");
	queryPost.whereEqualTo("text", "m");
	// "text is the attribute"; "m" is the value. It is like objectId and objectIdValue

	SubscriptionHandling<ParseObject> subscriptionHandling = parseLiveQueryClient.subscribe(queryPost);

	subscriptionHandling.handleEvents(new SubscriptionHandling.HandleEventsCallback<ParseObject>() {
		@Override
		public void onEvents(ParseQuery<ParseObject> query, SubscriptionHandling.Event event, ParseObject object) {
			Toast.makeText(getContext(), "onEvents called", Toast.LENGTH_LONG).show();
		}
	});

	subscriptionHandling.handleError(new SubscriptionHandling.HandleErrorCallback<ParseObject>() {
		@Override
		public void onError(ParseQuery<ParseObject> query, LiveQueryException exception) {
			Toast.makeText(getContext(), exception.getMessage(), Toast.LENGTH_LONG).show();
		}
	});

	subscriptionHandling.handleEvent(SubscriptionHandling.Event.UPDATE, new SubscriptionHandling.HandleEventCallback<ParseObject>() {
		@Override
		public void onEvent(ParseQuery<ParseObject> query, ParseObject object) {
			Toast.makeText(getContext(), "Updated", Toast.LENGTH_LONG).show();
		}
	});
} catch (URISyntaxException e){
	Toast.makeText(getContext(), e.getMessage(), Toast.LENGTH_LONG).show();
}
```

We did not look into server logs yet. But we will do. 

Thanks.

**Comment by rogerhu** [comment]
You've defined Posts in your live query updates right?

```
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  client
```

Yeah, VERBOSE=1, on Parse-server.

I'd also take out the where statement and see if events are firing in general.

**Comment by unheal1337** [comment]
We have defined Posts in our live query updates like you posted.
Comments aswell, but we do not have the Comments class created. Perhaps leads to errors?

Veborse is activated now on parse server. This is the interesting part of it. This log represents our Android application.

```
2017-03-22T19:11:03.356Z - Current client number: 1
2017-03-22T19:11:03.355Z - Push Response : "{\"op\":\"subscribed\",\"clientId\":0,\"requestId\":1}"
2017-03-22T19:11:03.354Z - Request: {"op":"subscribe","requestId":1,"sessionToken":"r:4fe26a4a3dc9c10b109895c59e26cd99","query":{"className":"Posts","where":{"text":"m"}}}
2017-03-22T19:11:03.240Z - Push Response : "{\"op\":\"connected\",\"clientId\":0}"
2017-03-22T19:11:03.235Z - Request: {"op":"connect","applicationId":"xxx","sessionToken":"r:4fe26a4a3dc9c10b109895c59e26cd99"}
2017-03-22T19:09:12.229Z - RESPONSE from [GET] /parse/classes/Posts: {
  "response": {
    "results": [],
    "count": 1
  }
}
2017-03-22T19:09:12.226Z - REQUEST for [GET] /parse/classes/Posts: {
  "where": {},
  "limit": 0,
  "count": 1
}
```

Have not tried without where statement yet.

**Comment by unheal1337** [comment]
We have tested LiveQuery on local ParseServer. That works!

Errors must occur at AWS. We are using AWS's Application Load Balancer (which is in beta) as mentioned. We also have tried with troubleshooting connectivity issues from https://aws.amazon.com/de/premiumsupport/knowledge-center/elb-connectivity-troubleshooting/

We are only able to open Load Balancers port 80 for HTTP traffic and port 443 for HTTPS. Nothing else is possible. 

Tomorrow we want to try running Parse Server on port 80.

**Comment by rogerhu** [comment]
You need to open for TCP too.

https://mitchellsimoens.com/websockets-behind-elastic-beanstalk/

**Comment by rogerhu** [comment]
This might be better for load balancing:

https://blog.jverkamp.com/2015/07/20/configuring-websockets-behind-an-aws-elb/

**Comment by unheal1337** [comment]
Running Parse Server on port 80 solved our problem. LiveQuery works fine. Thanks for the help and quick responses.

Issue can be closed now.
