### ISSUE TITLE
Missing tag for v1.0.0

### ISSUE THREAD

**Issue by jhansche** [ParsePlatform/ParseLiveQuery-Android#25]
1.0.0 was released Mar 10: https://mvnrepository.com/artifact/com.parse/parse-livequery-android/1.0.0

But that release was not tagged.  Looks like the commit that should be tagged is f96fefe, as the next commit is the 1.0.1-SNAPSHOT bump: https://github.com/ParsePlatform/ParseLiveQuery-Android/commits/d07b963

**Comment by mmimeault** [comment]
Yep. You are right. The release has been made manually. Travis is not yet configured to auto deploy release. I forgot the tag. Can you do it, or you want me to do it? The commit is right.

**Comment by jhansche** [comment]
I can do it.

**Comment by jhansche** [comment]
https://github.com/ParsePlatform/ParseLiveQuery-Android/releases
