### ISSUE TITLE
OkHttp WebSocket.close() status code is wrong

### ISSUE THREAD

**Issue by jhansche** [ParsePlatform/ParseLiveQuery-Android#38]
Per the javadoc for the `WebSocket.close()` endpoint, the valid status codes can be found at https://tools.ietf.org/html/rfc6455#section-7.4

Right now we're passing 200, which is in the `0-999` range that they describe as _not used_.

The standard status code appears to be `1000` for a typical close request.

**Comment by rogerhu** [comment]
Thanks.
