### ISSUE TITLE
Incomplete Pointer over LiveQuery destroys existing (complete) in-memory version of that object

### ISSUE THREAD

**Issue by jhansche** [ParsePlatform/ParseLiveQuery-Android#7]
Scenario:

1. Local Datastore is enabled
2. Receive a complete Parse Object by some means, e.g., Parse Cloud response; example: `{className:"Foo",objectId:"abcdefg",field:5}`
3. Receive a LiveQuery CREATE or UPDATE event for a _different_ object, where that LQ object contains a pointer reference to the same object that was complete in (2) above; example: `{__op:"create",object:{className:"Bar",objectId:"xxxxx","someField":{__type:"Pointer",className:"Foo",objectId:"abcdefg"}}}`
4. All references to the (2) object have now been replaced with the _incomplete_ `Pointer` reference due to the LQ's `someField` pointer. Meaning the previous instance from (2), where `obj.getInt("field") == 5` worked properly, would now result in an exception because the object is "incomplete" and would have to be re-fetched.

The only way to ensure this doesn't happen is to pin the objects in their complete state, and then remember to clean those up later.

The LiveQuery JSON decoder should use an existing in-memory object (if one exists) if it receives a `__type=Pointer` field in the LiveQuery event.  This may be a Parse-SDK-Android bug.

**Comment by jhansche** [comment]
Manipulating unit tests in Parse-SDK-Android for ParseDecoder, I found that this works properly:

```
ParseObject pointerObject = (ParseObject) ParseDecoder.get().decode(json);
```

but this results in erasing the original object:
```
ParseObject pointerObject = ParseObject.fromJSON(json, null, true, ParseDecoder.get());
```

The problem appears to stem from the `isComplete=true` parameter.  Passing `isComplete=false` once again reuses the original/existing object from the OfflineStore's cache of class+id pairs.  And that also continues to allow a new JSON payload to _update_ an existing object.

Because the isComplete parameter comes from `subscription.getQueryState().selectedKeys() == null`, we can probably work around this issue by requesting only a subset of keys on the subscription event (or even requesting all known keys).

**Comment by flovilmart** [comment]
Or we can use the ParseDecoder.get().decode(json) no?

**Comment by jhansche** [comment]
I believe that would also work, yes.  I just haven't been able to confirm that 100% yet.

**Comment by flovilmart** [comment]
TBC then :) thanks for the detailed report and investigation :)

**Comment by jhansche** [comment]
As it turns out, I believe I found the issue, and it's not directly related to LiveQuery.  The issue is that the in-memory cache of `{class,id}` pairs to the full object, which can be reused anytime that object it seen (including coming in as a `Pointer` object in LiveQuery), are only kept in memory as `WeakReference`s.  So once the original object is no longer strongly referenced, the in memory data goes away, and future uses of it will once again show only a `Pointer`.

The fix was to hold a strong reference to the object(s) until they are no longer needed.
