### ISSUE TITLE
What to pass for URI

### ISSUE THREAD

**Issue by kittuvenkat** [ParsePlatform/ParseLiveQuery-Android#9]
Could anyone provide information on what to pass for URI in below declaration?

ParseLiveQueryClient<ParseObject> parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(URI)

**Comment by kittuvenkat** [comment]
Ended up passing 'ws' instead of 'http' with host to make it work. Not sure if this is the right way to do it.

parseLiveQueryClient = ParseLiveQueryClient.Factory.getClient(new URI("ws://192.168.0.47:1337/"));

**Comment by mmimeault** [comment]
Hello,

Replacing http by ws or https by wss is the right solution.
This is expected. I will update the doc with that detail if it's not clear enough.

Thanks.
